### Lecture 24: Handing Missing Values Iterative Imputer

Steps

1. Checking columns with Nan Values (works best with MAR)
2. Splitting data into training & testing
3. Making object of Iterative Imputer class
4. Applying fit_transform on Training data & transform on Test data
   
    ###### As after fit_transform X_train & X_test will be numpy array so if you want you can change them back to data frame (your choice)

In [1]:

import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer # enables the imputer
from sklearn.impute import IterativeImputer # imputer itself

from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv('framingham.csv')
df.head(5)

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

Train Test Split

In [3]:
X=df.drop(columns='TenYearCHD',axis=1)
Y=df.TenYearCHD

In [4]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=42,test_size=0.2)

In [5]:
X_train.sample(10)

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose
3368,0,41,1.0,0,0.0,0.0,0,0,0,181.0,112.0,75.5,25.14,72.0,95.0
287,1,39,2.0,0,0.0,0.0,0,0,0,258.0,105.0,69.0,24.10,52.0,79.0
376,0,45,2.0,1,20.0,0.0,0,0,0,285.0,116.0,87.0,23.85,65.0,55.0
413,0,44,1.0,0,0.0,0.0,0,0,0,175.0,135.0,81.0,26.38,71.0,NaN
3069,1,63,1.0,1,6.0,0.0,0,1,0,256.0,138.5,77.5,28.85,80.0,84.0
4184,1,44,1.0,1,20.0,0.0,0,0,0,232.0,137.5,87.5,30.03,88.0,70.0
288,0,36,2.0,1,5.0,0.0,0,0,0,228.0,111.0,68.0,23.86,88.0,68.0
660,1,50,4.0,1,43.0,1.0,0,1,0,255.0,126.5,92.5,25.35,90.0,74.0
588,0,52,1.0,1,3.0,0.0,0,1,0,210.0,185.0,114.0,27.01,70.0,83.0
2777,0,42,4.0,0,0.0,0.0,0,0,0,278.0,118.5,72.0,21.99,72.0,78.0

Applying Iterative imputer

In [6]:
imputer = IterativeImputer(
    estimator=LinearRegression(),  
    max_iter=100,
    random_state=42,
    verbose=2
)

In [7]:
X_train.isnull().sum()

male                 0
age                  0
education           88
currentSmoker        0
cigsPerDay          24
BPMeds              48
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             42
sysBP                0
diaBP                0
BMI                 14
heartRate            1
glucose            314
dtype: int64

Applying Fit Transform

In [8]:
X_train['education']=imputer.fit_transform(X_train[['education']])
X_test['education']=imputer.transform(X_test[['education']])

X_train['glucose']=imputer.fit_transform(X_train[['glucose']])
X_test['glucose']=imputer.transform(X_test[['glucose']])

# X_train=imputer.fit_transform(X_train)
# X_test=imputer.fit_transform(X_test)

In [9]:
X_train=pd.DataFrame(X_train)
X_test=pd.DataFrame(X_test)

In [10]:
X_train

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose
3252,1,40,4.0,1,30.0,0.0,0,0,0,205.0,131.0,81.0,23.74,66.0,87.0
3946,0,57,2.0,0,0.0,0.0,0,1,0,250.0,152.5,92.5,32.31,75.0,94.0
1261,0,47,1.0,0,0.0,0.0,0,0,0,230.0,123.0,71.0,26.98,83.0,73.0
2536,1,41,2.0,1,30.0,0.0,0,0,0,228.0,113.0,82.5,25.67,67.0,70.0
4089,0,64,1.0,0,0.0,0.0,0,1,0,232.0,149.5,84.0,20.49,68.0,96.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3444,0,36,1.0,1,5.0,0.0,0,1,0,222.0,147.0,94.0,26.79,76.0,71.0
466,0,57,3.0,1,15.0,0.0,0,0,0,250.0,125.0,74.0,21.08,80.0,72.0
3092,0,60,2.0,0,0.0,0.0,0,1,0,298.0,133.0,89.0,25.09,83.0,81.0
3772,1,39,2.0,1,10.0,0.0,0,0,0,215.0,102.0,64.5,24.50,68.0,62.0
860,0,35,2.0,0,0.0,0.0,0,0,0,248.0,107.0,73.0,20.64,90.0,80.0

Checking Na values again

In [11]:
X_train.isnull().sum()

male                0
age                 0
education           0
currentSmoker       0
cigsPerDay         24
BPMeds             48
prevalentStroke     0
prevalentHyp        0
diabetes            0
totChol            42
sysBP               0
diaBP               0
BMI                14
heartRate           1
glucose             0
dtype: int64